//
//  DetailPresenter.swift
//  empresas
//
//  Created by Gustavo Chaves on 18/05/20.
//  Copyright (c) 2020 Gustavo Chaves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailPresentationLogic
{
  func presentSomething(response: Detail.Something.Response)
}

class DetailPresenter: DetailPresentationLogic
{
  weak var viewController: DetailDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Detail.Something.Response)
  {
    let viewModel = Detail.Something.ViewModel(name: response.name, description: response.description)
    viewController?.displaySomething(viewModel: viewModel)
  }
}
