//
//  LoginModels.swift
//  empresas
//
//  Created by Gustavo Chaves on 16/05/20.
//  Copyright (c) 2020 Gustavo Chaves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Login
{
  // MARK: Use cases
  
  enum Something
  {
    struct Request
    {
        var email: String
        var password: String
    }
    struct Response
    {
        var user: LoginResponse
        var headers: Headers
    }
    struct ViewModel
    {
    }
    struct LoginData{
        var email: String
        var password: String
    }
  }
    enum Error
    {
        struct ViewModel
        {
            var message: String
        }
    }
}
