//
//  LoginWorker.swift
//  empresas
//
//  Created by Gustavo Chaves on 16/05/20.
//  Copyright (c) 2020 Gustavo Chaves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class LoginWorker
{
  func doSomeWork()
  {
    Networking.shared.doLogin(email: "testeapple@ioasys.com.br", password: "12341234") { (LoginResponse) in
        print(LoginResponse)
        print("a")
    }
    
  }
}
