//
//  LoginRouter.swift
//  empresas
//
//  Created by Gustavo Chaves on 16/05/20.
//  Copyright (c) 2020 Gustavo Chaves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LoginRoutingLogic
{
  func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol LoginDataPassing
{
  var dataStore: LoginDataStore? { get }
}

class LoginRouter: NSObject, LoginRoutingLogic, LoginDataPassing
{
  weak var viewController: LoginViewController?
  var dataStore: LoginDataStore?
  
  // MARK: Routing
  
  func routeToSomewhere(segue: UIStoryboardSegue?)
  {
    if let segue = segue {
      let destinationVC = segue.destination as! HomeViewController
      var destinationDS = destinationVC.router!.dataStore!
      passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    } else {
        DispatchQueue.main.async {
            //let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let destinationVC =  HomeViewController()//storyboard.instantiateViewController(withIdentifier: "HomeViewController") as! HomeViewController
            var destinationDS = destinationVC.router!.dataStore!
            self.passDataToSomewhere(source: self.dataStore!, destination: &destinationDS)
            self.navigateToSomewhere(source: self.viewController!, destination: destinationVC)
        }
    }
  }

  // MARK: Navigation
  
  func navigateToSomewhere(source: LoginViewController, destination: HomeViewController)
  {
    //source.show(destination, sender: nil)
    //DispatchQueue.main.async {
        destination.modalPresentationStyle = .custom
        source.show(destination, sender: nil)
    //source.present(destination, animated: true, completion: nil)
    //}
  }
  
  // MARK: Passing data
  
  func passDataToSomewhere(source: LoginDataStore, destination: inout HomeDataStore)
  {
    destination.headers = source.headers
    destination.user = source.user
  }
}
